"""
PDF credit assessment report generator using fpdf2.

Produces a professional one-page report with:
  - Applicant summary table
  - Risk score with color-coded indicator
  - Top contributing factors from SHAP
  - Loan recommendation
  - Disclaimer
"""
from __future__ import annotations

import io
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from fpdf import FPDF


class CreditReportPDF(FPDF):
    """Custom PDF with header/footer for credit reports."""

    def header(self):
        self.set_font("Helvetica", "B", 18)
        self.set_text_color(30, 60, 120)
        self.cell(0, 12, "Credit Risk Assessment Report", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "", 9)
        self.set_text_color(120, 120, 120)
        ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        self.cell(0, 6, f"Generated: {ts}", align="C", new_x="LMARGIN", new_y="NEXT")
        self.line(10, self.get_y() + 2, 200, self.get_y() + 2)
        self.ln(6)

    def footer(self):
        self.set_y(-20)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(150, 150, 150)
        self.cell(0, 5, "DISCLAIMER: This report is generated by an AI model for demonstration purposes only.", align="C", new_x="LMARGIN", new_y="NEXT")
        self.cell(0, 5, "It should not be used for actual lending decisions. No personally identifiable information is stored.", align="C", new_x="LMARGIN", new_y="NEXT")
        self.cell(0, 4, f"Page {self.page_no()}/{{nb}}", align="C")


def _risk_color(prob: float) -> tuple[int, int, int]:
    """Return RGB color for risk level."""
    if prob > 0.6:
        return (214, 39, 40)      # red
    elif prob > 0.3:
        return (255, 127, 14)     # orange
    return (44, 160, 44)          # green


def _risk_label(prob: float) -> str:
    if prob > 0.6:
        return "HIGH RISK"
    elif prob > 0.3:
        return "MEDIUM RISK"
    return "LOW RISK"


def _create_shap_chart(names: list[str], svals: np.ndarray, top_n: int = 8) -> str:
    """Create a horizontal SHAP bar chart and return path to temp PNG."""
    order = np.argsort(np.abs(svals))[-top_n:]
    fig, ax = plt.subplots(figsize=(5.5, 3))
    colors = ["#d62728" if v > 0 else "#2ca02c" for v in svals[order]]
    ax.barh([names[i] for i in order], svals[order], color=colors, height=0.6)
    ax.set_xlabel("Impact on Default Risk", fontsize=8)
    ax.axvline(0.0, color="gray", linewidth=0.8)
    ax.tick_params(labelsize=7)
    plt.tight_layout()
    tmp = tempfile.NamedTemporaryFile(suffix=".png", delete=False)
    fig.savefig(tmp.name, dpi=150, bbox_inches="tight")
    plt.close(fig)
    return tmp.name


def generate_report(
    applicant: dict,
    probability: float,
    shap_names: list[str],
    shap_values: np.ndarray,
    loan_rec: dict | None = None,
) -> bytes:
    """Generate a PDF credit assessment report.

    Args:
        applicant: Dict of raw applicant inputs (age, monthly_income, etc.).
        probability: Default probability (0-1).
        shap_names: Feature names from SHAP.
        shap_values: SHAP values array.
        loan_rec: Optional loan recommendation dict.

    Returns:
        PDF file content as bytes.
    """
    pdf = CreditReportPDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=25)

    # --- Risk Score Section ---
    r, g, b = _risk_color(probability)
    label = _risk_label(probability)

    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(40, 40, 40)
    pdf.cell(0, 10, "Risk Assessment", new_x="LMARGIN", new_y="NEXT")

    # Risk score box
    pdf.set_fill_color(r, g, b)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 28)
    pdf.cell(60, 20, f" {probability:.0%}", fill=True, new_x="END")
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(70, 20, f"  {label}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # --- Applicant Information ---
    pdf.set_text_color(40, 40, 40)
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Applicant Profile", new_x="LMARGIN", new_y="NEXT")

    field_labels = {
        "age": "Age",
        "monthly_income": "Monthly Income",
        "debt_ratio": "Debt-to-Income Ratio",
        "revolving_util": "Credit Card Utilization",
        "n_30_59_late": "Times 30-59 Days Late",
        "n_60_89_late": "Times 60-89 Days Late",
        "n_90_late": "Times 90+ Days Late",
        "n_open_lines": "Open Credit Lines",
        "n_real_estate": "Real Estate Loans",
        "n_dependents": "Dependents",
    }

    pdf.set_font("Helvetica", "", 9)
    col_w = 95
    row_h = 7
    items = list(field_labels.items())
    for i in range(0, len(items), 2):
        for j in range(2):
            if i + j < len(items):
                key, lbl = items[i + j]
                val = applicant.get(key, "N/A")
                if key == "monthly_income":
                    val_str = f"${float(val):,.0f}"
                elif key in ("debt_ratio", "revolving_util"):
                    val_str = f"{float(val):.2f}"
                else:
                    val_str = str(int(float(val))) if val != "N/A" else "N/A"

                pdf.set_font("Helvetica", "B", 9)
                pdf.cell(35, row_h, f"{lbl}:")
                pdf.set_font("Helvetica", "", 9)
                nx = "END" if j == 0 else "LMARGIN"
                ny = "LAST" if j == 0 else "NEXT"
                pdf.cell(col_w - 35, row_h, val_str, new_x=nx, new_y=ny)
        if i + 1 >= len(items):
            pdf.ln(row_h)

    pdf.ln(4)

    # --- SHAP Chart ---
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(40, 40, 40)
    pdf.cell(0, 10, "Key Risk Factors (SHAP Analysis)", new_x="LMARGIN", new_y="NEXT")

    chart_path = _create_shap_chart(shap_names, shap_values)
    pdf.image(chart_path, x=15, w=170)
    pdf.ln(4)

    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 5, "Red bars increase default risk | Green bars decrease default risk", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    # --- Loan Recommendation ---
    if loan_rec:
        pdf.set_text_color(40, 40, 40)
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 10, "Loan Recommendation", new_x="LMARGIN", new_y="NEXT")

        rec_fields = [
            ("Decision", loan_rec.get("decision", "N/A")),
            ("Risk Tier", loan_rec.get("risk_tier", "N/A")),
            ("Suggested Rate Range", loan_rec.get("suggested_rate_range", "N/A")),
            ("Max Suggested Loan", loan_rec.get("max_suggested_loan", "N/A")),
            ("Max Monthly Payment", loan_rec.get("max_monthly_payment", "N/A")),
        ]
        pdf.set_font("Helvetica", "", 9)
        for lbl, val in rec_fields:
            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(50, 7, f"{lbl}:")
            pdf.set_font("Helvetica", "", 9)
            pdf.cell(0, 7, str(val), new_x="LMARGIN", new_y="NEXT")

        conditions = loan_rec.get("conditions", [])
        if conditions:
            pdf.ln(2)
            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(0, 7, "Conditions:", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 9)
            for cond in conditions:
                pdf.cell(10, 6, "")
                pdf.cell(0, 6, f"- {cond}", new_x="LMARGIN", new_y="NEXT")

    # --- Output ---
    try:
        import os
        os.unlink(chart_path)
    except OSError:
        pass

    return pdf.output()
